### ISSUE TITLE
What is the vision of this plugin?

### ISSUE THREAD

**Issue by voz** [phutchins/logstash-input-mongodb#1] opened 2015-03-02 12:45 UTC
Hey, I would like to input my mongodb data into elasticsearch via logstash. So I've searched for a logstash input plugin and this repo popped up.

@phutchins What is your vision for this plugin?

**Comment by phutchins** [comment] 2015-03-02 13:05
Hey, thats great. We have the same goal. I actually just started development on this plugin last week. I finished the first round Friday and am working on testing it now. I have a few other plans for features for the plugin so that it can be used by anyone that needs it so your help and input would be greatly appreciated!

@voz, currently we store our logs in capped collections in MongoDB. Each collection spans the logs for a day.

Here are my goals...
- create a plugin that can read the log entries from these collections
- add a timestamp by decoding the mongo ID
- Detect new collections and begin parsing logs from them as they are created without logstash restart
- Be able to match collections to parse logs from via wildcard or search (i.e. events_* or events_[date])
- Avoid hammering mongo on initial parse of logs
- Make the plugin sufficiently feature rich but not specific to my use case so that anyone can make use of it

What is your use case? Any thoughts to add to the goals?

**Comment by Analect** [comment] 2015-03-05 14:01
@phutchins 
As with @voz , I just happened upon this repo.
I would like to be able to leverage the bulk api in order to be able to set up parent-child relationships. So a collection may contain many fields, one of which could be used as a parent_id, with other fields fed to child document ... or perhaps the parent_id comes from another collection, where there is a common field between the collections. There is a tool from mongodb themselves that is an alternative to rivers: https://github.com/10gen-labs/mongo-connector.
However, it isn't handling parent-child / routing as yet
I've been using a river plugin for ES to get documents in gridFS indexed to ES, but I want to be able to handle setting a parent_id at index time for a body of legacy documents.

**Comment by phutchins** [comment] 2015-03-13 17:50
@Analect and @voz, take a look at what I have so far. This mostly fits my needs without being too specific. It seems like what you're wanting to do is a little different from my needs but I'd be glad to add functionality for your needs as well. 

Currently you feed this plugin a collection or part of a collection name and it will parse any collections that match that name. It will process batches of documents from each one after another until all documents are parsed. It will then watch those collections for new documents. I will be adding a bit that allows it to check for new collections that match the search every x minutes. This fits our needs because we create a log collection for each day.

It sounds like you want to specify a collection then specify a field in documents in that collection to gather or merge other documents with the initial document. Is that close to what you want to do?

**Comment by Analect** [comment] 2015-03-16 23:12
@phutchins 
Thanks for this. I'd like to test this. As yet, I don't think you have moved it to https://github.com/logstash-plugins, so a basic bin/plugin install logstash-input-mongodb isn't going to work.
I think the README is boilerplate for any new plugin ... could you give some quick guidance in terms of building the relevant gem file, which I can then point to for installing? I haven't installed one of these from source before.
Also, is there any special requirement for mongodb to be set up as a replicating cluster, or will it work with just a single mongo instance?
Finally, I was hoping to test using a gridFS collection (fs.files, fs.chunks).  Do you envisage any issues with this?
I'm hoping to use the metadata field in fs.files (http://docs.mongodb.org/manual/reference/gridfs/#gridfs-files-collection) to pass a parent_id to ES ... such that that id points to an attachment document already on ES that becomes the parent of the child files document, that will get pushed to ES via logstash ... if that makes sense. I'm not sure whether your input allows for this ... or indeed if I am able to use a ruby filter in conjunction with the mongodb-input to achieve this.
Would you have a sample logstash.conf file you are using for your own use-case?
Thanks again for your work on this.
Colum

**Comment by phutchins** [comment] 2015-03-17 13:47
@Analect I'm actually in the process of getting it accepted into the logstash-plugins repo. You can see the issue I opened to do that here: https://github.com/elastic/logstash/issues/2836

I do still need to write tests for it and update the readme with all of the available options and an example config file as you mentioned.

Regarding requirements for mongodb, this should work with any configuration as the mongo driver should handle that. I've tested it with a single node so far. I plan on doing more testing in the future.

To do what you're talking about with the parent_id, I can add a flag to add the mongodb document _id to a field called parent_id in elasticsearch. Is this what you're looking for?

To get you started, here is the config i'm using...

input {
  mongodb {
    uri => 'mongodb://mymongo.net/my-prod-log?ssl=true'
    path => '/home/user/logstash_sqlite.db'
    collection => 'events_'
    unpack_mongo_id => true
    batch_size => 5000
  }
}

filter {
  date {
    match => [ "logdate", "ISO8601" ]
  }
}

output {
  redis {
    host => "localhost"
    data_type => "list"
    key => "logstash-mykey"
  }
}

**Comment by Analect** [comment] 2015-03-17 15:52
@phutchins 
Thanks for the info.

Ref installing your plugin, I did the following, while the plugin remains external to the main logstash-plugins repo.

1. I cloned your repo and ran: gem build logstash-input-mongodb.gemspec
2. This generated a RubyGem, but with various warnings.
Successfully built RubyGem
  Name: logstash-input-mongodb
  Version: 0.1.0
  File: logstash-input-mongodb-0.1.0.gem
3. I then tried to install this on logstash 1.4.2, but got the following error.
bin/plugin install ../logstash-input-mongodb/logstash-input-mongodb-0.1.0.gem 
Can only install contrib at this time... Exiting.

4. I then tried on logstsash 1.5.0.rc2, but got the following error. 
logstash-1.5.0.rc2$ bin/plugin install logstash-input-mongodb-0.1.0.gem 
Validating logstash-input-mongodb-0.1.0.gem
Error reading plugin file logstash-input-mongodb-0.1.0.gem, caused by NameError
Installation aborted

What am I doing wrong?

Ref my use case, this gist might help to explain.
https://gist.github.com/clintongormley/7039568

I have an 'attachment' type in ES, which uses a UUID as its identifier. Back in mongodb, I have binary files in gridFS (fs.files, fs.chunks). I am looking to push across the ES, a document of type 'files', where the identifier is the mongodb _id, but where the parent (_parent fed to bulk api) is the attachment UUID, as described above. I could set things up such that this attachment UUID was either a metadata field in the fs.files collection, or have it in a separate collection ... for feeding to logstash and ultimately ES via your plugin. Does this make sense?  Is this something that you think your plugin could handle?
Being able to push across the attachment UUID as _parent at the same time as the 'files' mongodb ObjectId (as the main ES id for type files) is required such that the parent and child docs end up on the same shard and such that parent-child queries work properly.

**Comment by electrical** [comment] 2015-03-17 23:07
Hi guys,

with LS 1.5.0.RC2 the gem file installation is not functional.
That said the author can always publish the gem to rubygems and you can install it via the bin/plugin command.
Its fully separate of the logstash-plugins repo.
The plugins won't work with LS 1.4.x since the plugin management is made for 1.5 and higher.

**Comment by Analect** [comment] 2015-03-17 23:47
Thanks for the info @electrical

**Comment by phutchins** [comment] 2015-03-18 12:59
@electrical is exactly right. I will make a few changes to the plugin, publish the gem to rubygems and let you know when it's up.

**Comment by Analect** [comment] 2015-03-18 13:21
@phutchins . Great. thanks.
If you could have a glimpse over my use-case and see if that tallies at all with how you envisage extending the functionality.
Ref you logstash.conf sample above:
Is your collection called 'my-prod-log' or is the location of a mongodb log file? ... and is the logstash_sqlite.db used to buffer the items/events coming from mongodb?
Your output in this case is to redis .. what would it look like outputting to elasticsearch?
Thanks.

**Comment by phutchins** [comment] 2015-03-18 14:01
The gem has been published here: https://rubygems.org/gems/logstash-input-mongodb

@Analect re your use case, it looks like you're trying to pull attachments from mongo into ES as type attachment and pull an ID from mongo that would be used in ES as a parent ID. If you could outline (in JSON or similar) how the doc(s) in mongo would look, then how you desire it to look in ES after it is processed, that would be very helpful. I have no doubt that we can get my plugin working for your use case...

Re the config, my-prod-log is the MongoDB database name. I'm using a standard mongo URI. The collection attribute specifies the collection regex to use to when finding collections to monitor for new entries. I'd like to change it such that you can either use collection_regex, or collection to specify that you want to use a regex to find multiple collections or simply specify a single collection.

I assume for pulling a child document from mongo, we could have something like...
```
input {
  mongodb {
    uri => 'mongodb://mymongo.net/my-prod-log?ssl=true'
    path => '/home/user/logstash_sqlite.db'
    collection => 'events_'
    child_collection_id_field => 'event_stack_trace'
    child_collection => 'stack_traces'
    merge_child_doc_field_name => 'stack_trace'
    unpack_mongo_id => true
    batch_size => 5000
  }
}
```

... which would allow me to pull the stack trace from a separate collection using a document ID in 'event_stack_trace' to find that doc in the 'stack_traces' collection and add it to the logstash event as event['stack_trace']. If you're not using Kibana to view this data, there would be no need to flatten the JSON or hash so it could be added to the event as I mentioned above.

**Comment by Analect** [comment] 2015-03-19 17:48
@phutchins 
Thanks for your efforts on this.
I'm hoping the image below (which I think you can enlarge) might help to better articulate things. I've mocked up the data ... and not everything in mongodb (in yellow on left) ends up in ES (in green on right).
The basic structure is that a note (Notes collection) can have multiple attachments (Attachments) and each attachment has a single file (fs.files collection in gridFS) that can have multiple chunks (fs.chunks).

The chunks are linked back to the files by file_id, the files are linked back to the attachments by gridFSId and the attachments are linked back to notes by attachId = link_to_attachID. Sorry if it's a bit convoluted.

Anyway, the idea is to migrate this to ES 'content' index where there are 3 types ... Notes, Attachments (with _parent corresponding to the relevant Note) and Files (with _parent corresponding to the Attachment).

The Files type leverages the mapper-attachment to bring file contents across in binary form and have them run through tika so that they are searchable. The idea is that if a search result gets surfaced in a File, that the various parent-child chains allows me to return the related 'Note', if that makes sense.

I had been using UUIDs as identifiers in ES, but I can go with using the mongo objectID for this data to simplify things, unless there is some easy approach to converting those identifiers on-the-fly.  Maybe your unpack_mongo_id does something like this ... I see your plugin also handles converting mongo datetime types.

![mongo_to_es](https://cloud.githubusercontent.com/assets/4063815/6736724/7a8a941c-ce5e-11e4-9c16-0fab66887ca0.PNG)

**Comment by Analect** [comment] 2015-03-24 22:48
@phutchins 
Did I overwhelm you with the last comment!
Perhaps I need to back-track a bit and fit my needs around what you think is feasible to deliver in terms of what you were originally envisaging.

**Comment by phutchins** [comment] 2015-03-24 22:52
Hey @analect, no not at all. :) just been super busy and haven't had a chance to take a deeper look. What you're doing sounds like a great application of this plug in and I'd like to implement it. We have to think of the best way to do this such that others can use it easily also...

**Comment by Analect** [comment] 2015-03-25 06:58
Understood. Just let me know if I can be of further help.

**Comment by phutchins** [comment] 2015-04-10 17:05
Still have not forgotten about this! I took a brief look and it looks like there should be no problem doing this.

How do you imagine that you would describe this in the configuration?

I think we should be able to do something like this...

input {
  mongodb {
    uri => 'mongodb://10.0.0.30/my-logs?ssl=true'
    path => '/opt/logstash-mongodb/logstash_sqlite.db'
    collection => 'Notes'
    unpack_mongo_id => true
    batch_size => 5000
    populate_children => {
      "Notes" => {
        id_field => "link_to_attachID"
        child_collection => "Attachments" # Where the child document is located
        child_type => "fs"  # This would specify how we need to handle the child
        destination_field_name => "attachment"
      }
  }
}

This way if we pull a document from the Notes collection, it checks for the id_field and gets that document from the child_collection. If the child_type is 'fs' we could tack on a bit to process the fs data type appropriately.

Note that my example config is a little backwards from your diagram. It looks like your parent document doesn't contain a link to the child but the other way around. Is there ant reason you wouldn't link to the attachment and data from the parent document? That way you could find the child doc without having to search all child docs for the one that contains the parent id? Please correct me if i'm on the wrong track regarding what you're trying to do and why...

**Comment by Analect** [comment] 2015-04-10 18:44
@phutchins 
Thanks for the update.
My approach, in terms of emphasising the parent, I suppose is based on the requirement to specify a 'parent id' as a child document is being indexed ... as per the bulk API etc.. such that the parent and child docs end up on the same shard (http://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html). I'm guessing that your implementation leverages the bulk API.

My requirement is to be able to retrieve 'parents' of documents (their children) surfaced in a search using the has_child query.  So, for a relevant term being found in an Attachment, I want to be able to bring back the associated Note. I think perhaps the introduction of inner hits in 1.5 (https://www.elastic.co/blog/elasticsearch-1-5-0-released) simplifies this process.

Anyway, coming back to your approach .. I think starting at the top of a hierarchy in mongoDB and specifying children can work too.  Perhaps I need to clarify a few things though, as per my example.

When you specify:
```
populate_children => {
      "Notes" => {
        id_field => "link_to_attachID"
        child_collection => "Attachments" # Where the child document is located
```
... it appears to assume that the mapping is to the default _id in the 'Attachments' collection = "link_to_attachID" in the Notes collection.  In fact, my data isn't as clear-cut.  In my example it is the 'attachId' in Attachments that equates to the 'link_to_attachID' in the Notes collection ... so the _id from neither collection is being considered. If you are able to handle that situation, then the configuration should probably explicitly specify the field names in parent and child collections and perhaps default to _id if not specified.

In the case of my second parent-child r'ship (that of Attachments to Files), that does include the _id for Files, but a non-default 'gridFSId' field for the parent, in this case.  This second relationship will involve setting the child-type 'fs', which will need to handle sending the binary file such that it gets handled by the mapper-attachment.

Just for avoidance of doubt, to implement the two different parent-child relationships would require two separate {input {mongodb}} blocks. Correct?

Thanks ... and please come back if I can offer any further clarification.

**Comment by Analect** [comment] 2015-04-24 08:10
@phutchins 
Can I be of further help here?

**Comment by phutchins** [comment] 2015-04-24 20:40
Hey @Analect, yeah if you could lay out what you would imagine the config would look for your situation it might help to expose the functionality that is needed.

Do you have any development experience? If so maybe you could fork my repo, take a stab at it and create a merge request. If not no worries, I'd be glad to continue working with you to try to get it working in a way that covers your situation but progress may be a bit slow as I'm having trouble finding spare time lately.

You might take a look at the dig method that I've created which selectively takes fields from the document as a nested hash and converts it to a single level hash. A similar concept could be used to do what you're describing by specifying the source document and destination document, and which fields should map to each other. It sounds like you would need two of these blocks as you have two different cases.

The mocked up config would be greatly helpful...

**Comment by phutchins** [comment] 2015-08-11 15:23
Hey @Analect I've actually got time to work on this again and have made some changes for the newer versions of logstash.

If you're still interested, a mocked up config describing what you'd expect would be really helpful. That along with the sample DB images that you provided and a desired output.

Do you do any coding by chance? Always happy to accept pull requests if you want to get your hands dirty!

**Comment by phutchins** [comment] 2015-12-16 12:43
Going to close this since it's been dead for so long. If you still have a need or interested in working on this, let me know and I'll open discussion back up.

**Closed by phutchins** 2015-12-16 12:43 UTC

**Comment by Analect** [comment] 2015-12-18 14:22
Sorry @phutchins 
Thanks for your offer to help here ... but ended up using a different approach.

**Comment by phutchins** [comment] 2015-12-18 15:00
@Analect of course. Glad you found a way to do what you were trying to do!

**Comment by puneetjindal** [comment] 2016-02-25 11:14
@phutchins : I am really concerned about the 3rd goal that you have mentioned i.e. "Detect new collections and begin parsing logs from them as they are created without logstash restart". It seems that this feature is not available yet

**Comment by phutchins** [comment] 2016-02-26 02:19
@puneetjindal, the 3rd goal does actually work. This is the way that I've used this plugin for quite some time.

**Comment by puneetjindal** [comment] 2016-02-26 02:39
@phutchins: what I understand from third goal is that I should not specify any collection name. The moment a new collection is added to Mongo it starts syncing the new collection.
Another question is how can I tail on Oplog with the help of this plugin?
Third question:- if I want to integrate it into my Java application where I am using this plugin for data ingestion, does it provide any API?

**Comment by phutchins** [comment] 2016-03-01 23:32
@puneetjindal you do need to specify a collection name using a regular expression.
